language: go
dist: trusty

go:
  - 1.8.x

branches:
  only:
    - master

install:
  - go get -v github.com/IgnacioCarbajoVallejo/go-zfs
  - go get -v github.com/pborman/uuid
  - go get -v github.com/pborman/getopt/v2
  - go get -v github.com/sevlyar/go-daemon
  - go get -v github.com/kardianos/osext
  - go get -v github.com/golang/lint/golint

script:
  - go test -v ./...
  - go vet -v ./...
  - golint .

notifications:
  email: false

sudo: false
